# Generated by Django 5.0.11 on 2025-03-03 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=150, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyID', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=150)),
                ('CompanyEmail', models.EmailField(max_length=255)),
                ('CompanyPhone', models.CharField(max_length=20)),
                ('CompanyAddress', models.TextField()),
                ('CompanyIndustry', models.CharField(max_length=100)),
                ('CompanySize', models.CharField(max_length=20)),
                ('ContactPersonName', models.CharField(max_length=150)),
                ('ContactPersonEmail', models.EmailField(max_length=255)),
                ('ContactPersonPhone', models.CharField(max_length=20)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=255)),
                ('JobDescription', models.TextField()),
                ('JobLocation', models.CharField(max_length=255)),
                ('JobRequirements', models.TextField()),
                ('JobType', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20)),
                ('ApplicationDeadline', models.DateField()),
                ('ManpowerRequired', models.IntegerField()),
                ('SalaryType', models.CharField(choices=[('Manual', 'Manual'), ('Range', 'Range'), ('Negotiable', 'Negotiable')], max_length=20)),
                ('SalaryManual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SalaryRangeMin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SalaryRangeMax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('interpersonal_skills', models.TextField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationID', models.CharField(default='default_value', max_length=100)),
                ('AppliedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobpostings')),
                ('job_seeker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobseekers')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('job_seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobseekers')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('seeker', 'Job Seeker'), ('employer', 'Employer')], default='seeker', max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
