# Generated by Django 5.0.11 on 2025-03-05 05:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekers',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to=core.models.profile_picture_path),
        ),
    ]
