# Generated by Django 5.0.11 on 2025-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='company_logos/default_logo.png', null=True, upload_to='company_logos/'),
        ),
    ]
